name: Qt CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]

    steps:
    - uses: actions/checkout@v4
    - name: Install libusb
      if: runner.os == 'Linux'
      run: |
          sudo apt update
          sudo apt install libusb-1.0-0-dev
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        modules: qtwebchannel qtpositioning qtserialport qt5compat qtwebengine
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: lukka/run-vcpkg@v11
    - name: Build on ${{ matrix.os }}
      shell: cmd
      if: runner.os == 'Windows'
      run: |
        vcpkg install libusb
        md build
        cd build
        qmake ../qserial.pro
        nmake
    - name: Build on ${{ matrix.os }}
      shell: bash
      if: runner.os != 'Windows'
      run: |
        mkdir build
        cd build
        qmake ../qserial.pro
        make -j$(nproc)
        
    - name: Deploy (Windows)
      if: matrix.os == 'windows-latest'
      run: windeployqt build/QSerial.exe

    - name: Deploy (macOS)
      if: matrix.os == 'macos-15'
      run: macdeployqt build/QSerial.app -dmg

    - name: Deploy (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        # Example using linuxdeployqt or creating a simple tarball
        tar -czvf QSerial-Linux.tar.gz build/QSerial

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qserial-${{ matrix.os }}
        path: |
          build/*.exe
          *-Linux.tar.gz
          build/*.dmg
        if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
